version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    command: ["python", "app/main.py"]
    healthcheck:
      test: curl -sS http://127.0.0.1/health/ || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
  redis:
    image: redis
    ports:
      - "6379"